# backend
lucene_search.controller.admin.get_state:
    path: /admin/lucene-search/settings/get/state
    defaults: { _controller: LuceneSearchBundle:Admin\Settings:getState }
lucene_search.controller.admin.get_logs:
    path: /admin/lucene-search/settings/logs/get
    defaults: { _controller: LuceneSearchBundle:Admin\Settings:getLog }
lucene_search.controller.admin.crawler.start:
    path: /admin/lucene-search/settings/crawler/start
    defaults: { _controller: LuceneSearchBundle:Admin\Settings:startCrawler }
lucene_search.controller.admin.crawler.stop:
    path: /admin/lucene-search/settings/crawler/stop
    defaults: { _controller: LuceneSearchBundle:Admin\Settings:stopCrawler }

# frontend
lucene_search.controller.auto_complete.search:
    path: /lucence-search/auto-complete
    defaults: { _controller: LuceneSearchBundle\Controller\AutoCompleteController:searchAction }