services:

    LuceneSearchBundle\Command\CrawlCommand:
        autowire: true
        autoconfigure: true

    LuceneSearchBundle\Command\DocumentModifierCommand:
        autowire: true
        autoconfigure: true
