services:

   LuceneSearchBundle\Controller\FrontendController:
        autowire: true

   LuceneSearchBundle\Controller\AutoCompleteController:
        parent: LuceneSearchBundle\Controller\FrontendController
        autowire: true

   LuceneSearchBundle\Controller\SiteMapController:
        parent: LuceneSearchBundle\Controller\FrontendController
        autowire: true

   LuceneSearchBundle\Controller\ListController:
        parent: LuceneSearchBundle\Controller\FrontendController
        autowire: true
        calls:
            - [setHighlighterHelper, ['@LuceneSearchBundle\Helper\HighlighterHelper']]