services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # event listener
    LuceneSearchBundle\EventListener\MaintenanceQueueListener:
        tags:
            - { name: pimcore.maintenance.task, type: lucene_run_queued_document_modifier }

    LuceneSearchBundle\EventListener\MaintenanceRunCrawlerListener:
        tags:
            - { name: pimcore.maintenance.task, type: lucene_run_crawler }

    LuceneSearchBundle\EventListener\DocumentMetaDataListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }