services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LuceneSearchBundle\Modifier\QueuedDocumentModifier: ~

    LuceneSearchBundle\Modifier\DocumentModifier: ~
