services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # twig extensions
    LuceneSearchBundle\Twig\Extension\PaginationExtension:
        tags:
            - { name: twig.extension }

    LuceneSearchBundle\Twig\Extension\CrawlerExtension:
        tags:
            - { name: twig.extension }

    LuceneSearchBundle\Twig\Extension\CategoriesExtension:
        tags:
            - { name: twig.extension }