services:

    # tool installer
    lucene_search.tool.installer:
        class: LuceneSearchBundle\Tool\Install
        arguments: ['@logger']
        tags:
            - { name: monolog.logger }

    # tool crawler state
    lucene_search.tool.crawler_state:
        class: LuceneSearchBundle\Tool\CrawlerState

    # configuration
    lucene_search.configuration:
        class: LuceneSearchBundle\Configuration\Configuration
        arguments:
            - '@pimcore.extension.bundle_manager'

    # organizer dispatcher
    lucene_search.organizer.handler_dispatcher:
        class: LuceneSearchBundle\Organizer\Dispatcher\HandlerDispatcher
        arguments:
            - '@lucene_search.organizer.state_handler'
            - '@lucene_search.organizer.store_handler'

    # organizer handler
    lucene_search.organizer.abstract_handler:
        class: LuceneSearchBundle\Organizer\Handler\AbstractHandler
        abstract: true
        arguments:
            - '@lucene_search.configuration'
            - '@translator'

    lucene_search.organizer.state_handler:
        parent: lucene_search.organizer.abstract_handler
        class: LuceneSearchBundle\Organizer\Handler\StateHandler
    lucene_search.organizer.store_handler:
        parent: lucene_search.organizer.abstract_handler
        class: LuceneSearchBundle\Organizer\Handler\StoreHandler

    # task manager
    lucene_search.task_manager:
        class: LuceneSearchBundle\Task\TaskManager
        calls:
            - ['setTaskIterators', ['@=service("lucene_search.configuration").getConfig("seeds")']]

    # abstract task
    lucene_search.task.abstract_task:
        class: LuceneSearchBundle\Task\AbstractTask
        abstract: true
        arguments:
            - '@lucene_search.configuration'
            - '@lucene_search.organizer.handler_dispatcher'

    # tasks
    lucene_search.task.start_up:
            parent: lucene_search.task.abstract_task
            class: LuceneSearchBundle\Task\System\StartUpTask
            tags:
                - { name: lucene_search.task, priority: 80 }
    lucene_search.task.crawler:
            parent: lucene_search.task.abstract_task
            class: LuceneSearchBundle\Task\Crawler\CrawlerTask
            tags:
                - { name: lucene_search.task, priority: 60 }
    lucene_search.task.parser:
            parent: lucene_search.task.abstract_task
            class: LuceneSearchBundle\Task\Parser\ParserTask
            tags:
                - { name: lucene_search.task, priority: 40 }
    lucene_search.task.sitemap:
            parent: lucene_search.task.abstract_task
            class: LuceneSearchBundle\Task\Sitemap\SitemapTask
            tags:
                - { name: lucene_search.task, priority: 20 }
    lucene_search.task.shut_down:
            parent: lucene_search.task.abstract_task
            class: LuceneSearchBundle\Task\System\ShutDownTask
            tags:
                - { name: lucene_search.task, priority: 0 }

    # event listener
    lucene_search.event_listener.maintenance:
        class: LuceneSearchBundle\EventListener\CrawlListener
        arguments:
            - '@lucene_search.organizer.handler_dispatcher'
            - '@lucene_search.task_manager'

        tags:
            - { name: kernel.event_listener, event: pimcore.system.maintenance, method: run }

    # controller
    lucene_search.controller.frontend:
        class: LuceneSearchBundle\Controller\FrontendController
        methods:  [GET]
        arguments:
            - '@request_stack'
            - '@templating'
            - '@lucene_search.configuration'
            - '@lucene_search.helper.lucene'
            - '@lucene_search.helper.string'
    lucene_search.controller.frontend.auto_complete:
        class: LuceneSearchBundle\Controller\AutoCompleteController
        parent: lucene_search.controller.frontend
        methods: [GET]
    lucene_search.controller.frontend.sitemap:
        class: LuceneSearchBundle\Controller\SiteMapController
        parent: lucene_search.controller.frontend
        methods: [GET]
    lucene_search.controller.frontend.list:
        class: LuceneSearchBundle\Controller\ListController
        parent: lucene_search.controller.frontend
        methods: [GET]
        calls:
             - [setHighlighterHelper, ['@lucene_search.helper.highlighter']]

    # helper
    lucene_search.helper.lucene:
        class: LuceneSearchBundle\Helper\LuceneHelper
    lucene_search.helper.string:
        class: LuceneSearchBundle\Helper\StringHelper
    lucene_search.helper.highlighter:
        class: LuceneSearchBundle\Helper\HighlighterHelper

    # twig extensions
    lucene_search.twig.extension.pagination:
        class: LuceneSearchBundle\Twig\Extension\PaginationExtension
        public: false
        tags:
            - { name: twig.extension }
    lucene_search.twig.extension.crawler_state:
        class: LuceneSearchBundle\Twig\Extension\CrawlerExtension
        public: false
        arguments:
            - '@lucene_search.tool.crawler_state'
        tags:
            - { name: twig.extension }
    lucene_search.twig.extension.categories:
        class: LuceneSearchBundle\Twig\Extension\CategoriesExtension
        public: false
        arguments:
            - '@lucene_search.configuration'
        tags:
            - { name: twig.extension }