lucene_search:

    enabled: false

    fuzzy_search_results: false
    search_suggestion: true

    own_host_only: false

    seeds: []
    categories: ~

    filter:
        valid_links: []
        user_invalid_links: []
        core_invalid_links: '@.*\.(js|JS|gif|GIF|jpg|JPG|png|PNG|ico|ICO|eps|jpeg|JPEG|bmp|BMP|css|CSS|sit|wmf|zip|ppt|mpg|xls|gz|rpm|tgz|mov|MOV|exe|mp3|MP3|kmz|gpx|kml|swf|SWF)$@'

    allowed_mime_types:
        - 'text/html'
        - 'application/pdf'
    allowed_schemes:
        - 'http'

    crawler:
        max_link_depth: 15
        max_download_limit: 0
        content_max_size: 0
        content_start_indicator: ~
        content_end_indicator: ~
        content_exclude_start_indicator: ~
        content_exclude_end_indicator: ~

    sitemap:
        render: false

    locale:
        ignore_language: false
        ignore_country: true

    restriction:
        enabled: false

    auth:
        enabled: false
        api_token: ~

    boost:
        documents: 1
        assets: 1

    view:
        max_per_page: 10
        max_suggestions: 10